storeName: Commercia
subtitle: The best ecommerce on the web
baseurl: ""
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
 products:
  output: true

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
