storeName: Commercia
subtitle: The best ecommerce on the web

# Build settings
plugins:
  - jekyll-sitemap

collections:
 products:
  output: true

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
