storeName: Commercia
subtitle: The best ecommerce on the web
baseurl: ""
phone: "+55 11 91234-5678"
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
 - products

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
